medical_warehouse:
  outputs:
    dev:
      type: postgres
      threads: 1
      host: localhost
      port: 5433
      user: sa
      password: "123"
      dbname: medical_db
      schema: public
  target: dev
