version: 2

models:
  - name: stg_telegram_messages
    description: "Staging model for Telegram messages, cleaned and type-cast."
    columns:
      - name: message_id
        description: "Primary key (non-unique as one ID can span multiple rows if not handled, but here expected unique per channel)."
        tests:
          - not_null
      - name: channel_name
        tests:
          - not_null
