version: 2

sources:
  - name: public
    database: medical_db
    schema: public
    tables:
      - name: raw_messages

models:
  - name: stg_messages
    description: "Staging table for Telegram messages"
    columns:
      - name: id
        description: "Primary key"
        tests:
          - unique
          - not_null
